# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e24c792df069375bed93c3565dc58b1f9d079bf257bdd38ba4b90e34969a1cb80141de974199489729e08aec03d10f57a1c537392f42bf3fcc26bda53c5205f

test:
  secret_key_base: 053ad5dfa669cb8ad9e4f47f163c42394fec99da1616b2c4c4f6c4f37ecafab0ea344f8ade97bc89cc482bc2f7a036e5842ab5c64e3efea1d9b0d19037a11b02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
